[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cell-counter"
version = "1.2.0"
description = "Filtering micropatterned timelapse microscopy images based on number of cells"
authors = [
    {name = "Tianyi Cao", email = "ctyjackcao@outlook.com"},
]
dependencies = [
    "numpy>=1.24.0,<2.0.0",
    "torch>=2.0.0,<3.0.0",
    "imageio>=2.30.0,<3.0.0",
    "matplotlib>=3.7.0,<4.0.0",
    "opencv-python>=4.8.0,<5.0.0",
    "cellpose>=3.0.0",
    "nd2reader>=3.3.0,<4.0.0",
]
requires-python = ">=3.12,<4.0"
readme = "README.md"
license = {text = "MIT"}

[tool.hatch.build.targets.wheel]
packages = ["src/cell_counter"] 