[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cell-counter"
version = "0.1.0"
description = "A tool for counting cells in images"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "opencv-python",
    "torch",
    "torchvision",
    "pillow",
    "scikit-learn",
]