[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cell-counter"
version = "2.0.0"
description = ""
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
dependencies = []
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[tool.hatch.build.targets.wheel]
packages = ["src/cell_counter"]